baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Kamarul's website"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Me"
    url = "/about/"
[[menu.main]]
    name = "My GitHub"
    url = "http://drkamarul.github.io/"
[[menu.main]]
    name = "My Twitter"
    url = "https://twitter.com/kamarul_imran"

[params]
    description = "A personal website of Kamarul Imran Musa built through Hugo and blogdown with the helps of rbind community."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

